spring.application.name=backend

spring.datasource.url=jdbc:mariadb://192.168.3.13:3306/health_care?useSSL=false&useAuth=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

jwt.secret=mySecretKeyThatIsVeryLongAndSecureForJWTTokenGeneration123456789
jwt.expiration=86400000

openapi.service-key=

kakao.rest-api-key=${KAKAO_REST_API_KEY:ed628c178074ec79a99bec2c944f364d}

tmap.api-key=${TMAP_API_KEY:2P5SraBAF69IDMQPgTOQf3K3azhAiJJsZWcYR2T2}

spring.jackson.serialization.fail-on-empty-beans=false