spring.application.name=backend

spring.datasource.url=jdbc:mariadb://192.168.3.13:3306/health_care?useSSL=false&useAuth=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

jwt.secret=mySecretKeyThatIsVeryLongAndSecureForJWTTokenGeneration123456789
jwt.expiration=86400000

# 공공데이터 API 키
openapi.service-key=gPtV22mJezBSA5%2Bg8qhMQPCcx%2F8yr7SBcca0o4dmBLjzvpKuKfV%2FEwXTb%2Bq3Ps3buuhRP9sOlhqZSCSPMLoKzg%3D%3D

# Kakao API 키
kakao.rest-api-key=ed628c178074ec79a99bec2c944f364d

spring.jackson.serialization.fail-on-empty-beans=false