#  -Dspring.profiles.active=local-home      # 집에서 실행 시
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/health_care
#    url: jdbc:mariadb://127.0.0.1:3306/health_care  #안되면 이쪽으로
    username: root
    password: 1234
